name: AXFR Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag axfr:k8s
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        registry: dockr.it
        username: ${{ secrets.DOCKR_USER }}
        password: ${{ secrets.DOCKR_PASS }}
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: dockr.it/axfr
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.ref_type == 'tag' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
